[package]
name = "csvgen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
rand = "0.8.5"
tempfile = "3.10.1"
fastrand = "2.1.0"


[profile.release]
debug = true